-- PROGRESSION - 1


-- 1. **Create table city**
CREATE TABLE CITY (
ID NUMBER(11) PRIMARY KEY , NAME VARCHAR(50) NOT NULL
);
-- 2. **Create table referee**
 CREATE TABLE REFREE 
 (
    ID NUMBER(11) PRIMARY KEY , NAME VARCHAR(50) NOT NULL
 );
-- 3. **Create table innings**
CREATE TABLE INNINGS 
(
    ID NUMBER(11) PRIMARY KEY, INNINGS_NUMBER NUMBER(11)
);

-- 4. **Create table extra_type**
CREATE TABLE EXTRA_TYPE 
(
    ID NUMBER(11) PRIMARY KEY , NAME VARCHAR(50) NOT NULL
);

-- 5. **Create table skill**
CREATE TABLE SKILLS
(
    ID NUMBER(11) PRIMARY KEY, NAME VARCHAR(50) NOT NULL
);
select * from TEAM;

-- 6. **Create table team**

CREATE TABLE TEAM ( ID NUMBER(11) PRIMARY KEY, NAME VARCHAR(50)NOT NULL, COACH VARCHAR(50)NOT NULL,
HOME_CITY NUMBER(11)NOT NULL, CAPTAIN NUMBER(11) NOT NULL,
CONSTRAINT FK_TEAM_HOME_CITY FOREIGN KEY(HOME_CITY) REFERENCES CITY(ID)
);

-- 7. **Create table player**
DESC PLAYER;

CREATE TABLE PLAYER(ID NUMBER(11)PRIMARY KEY,NAME VARCHAR(50)NOT NULL, COUNTRY VARCHAR(50) NOT NULL,
SKILL_ID NUMBER(11) NOT NULL, TEAM_ID NUMBER(11) NOT NULL,
CONSTRAINT FK_PLAYER_SKILL FOREIGN KEY (SKILL_ID) REFERENCES SKILL(ID),
CONSTRAINT FK_PLAYER_TEAM FOREIGN KEY (TEAM_ID) REFERENCES TEAM(ID));

-- 8. **Create table venue**

CREATE TABLE VENUE ( ID NUMBER(11), STADIUM_NAME VARCHAR(50) NOT NULL, CITY_ID NUMBER(11) NOT NULL,
CONSTRAINT PK_VENUE_ID PRIMARY KEY(ID),
CONSTRAINT FK_VENUE_CITY_ID FOREIGN KEY (CITY_ID) REFERENCES CITY(ID));



-- 9. **Create table event**

CREATE TABLE EVENT( ID NUMBER(11) PRIMARY KEY , INNINGS_ID NUMBER(11) NOT NULL, EVENT_NO NUMBER(11)NOT NULL,
RAIDER_ID NUMBER(11) NOT NULL, RAID_POINTS NUMBER(11)NOT NULL, DEFENDING_POINTS NUMBER(11) NOT NULL, CLOCK_IN_SECONDS  NUMBER(11) NOT NULL,
TEAM_ONE_SCORE NUMBER(11) NOT NULL, TEAM_TWO_SCORE NUMBER(11)NOT NULL);
ALTER TABLE EVENT ADD CONSTRAINT FK_EVENT_RAIDER FOREIGN KEY (RAIDER_ID) REFERENCES PLAYER(ID);
ALTER TABLE EVENT ADD CONSTRAINT FK_EVENT_INNINGS FOREIGN KEY (INNINGS_ID) REFERENCES INNINGS(ID);

-- 10. **Create table extra_event**

CREATE TABLE EXTRA_EVENT (ID NUMBER(11) PRIMARY KEY , EVENT_ID NUMBER(11) NOT NULL,
EXTRA_TYPE_ID NUMBER(11) NOT NULL, POINTS NUMBER(11)NOT NULL, SCORING_TEAM_ID NUMBER(11)NOT NULL);
ALTER TABLE EXTRA_EVENT ADD CONSTRAINT FK_EXTRA_EVENT_ID FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID);
ALTER TABLE EXTRA_EVENT ADD CONSTRAINT FK_EXTRA_EVENT_EXTRA_ID FOREIGN KEY (EXTRA_TYPE_ID) REFERENCES EXTRA_TYPE(ID);
ALTER TABLE EXTRA_EVENT ADD CONSTRAINT FK_EXTRA_EVENT_TEAM_ID FOREIGN KEY (SCORING_TEAM_ID) REFERENCES TEAM(ID);


-- 11. **Create table outcome**

CREATE TABLE OUTCOME(ID NUMBER(11) PRIMARY KEY, STATUS VARCHAR(50) NOT NULL,WINNER_TEAM_ID NUMBER(11),
SCORE NUMBER(11), PLAYER_OF_MATCH NUMBER(11),
CONSTRAINT FK_KEY_OUTCOME_WINNER_TEAM FOREIGN KEY(WINNER_TEAM_ID) REFERENCES TEAM(ID),
CONSTRAINT FK_KEY_OUTCOME_PLAYER FOREIGN KEY(PLAYER_OF_MATCH) REFERENCES PLAYER(ID));

-- 12. **Create table game**

CREATE TABLE GAMES(ID NUMBER(11) PRIMARY KEY,GAME_DATE DATE, TEAM_ID_1 NUMBER(11) NOT NULL,TEAM_ID_2 NUMBER(11)NOT NULL,
VENUE_ID NUMBER(11) NOT NULL, OUTCOME_ID NUMBER(11)NOT NULL, REFEREE_ID_1 NUMBER(11)NOT NULL, REFEREE_ID_2 NUMBER(11) NOT NULL,
FIRST_INNINGS_ID NUMBER(11) NOT NULL, SECOND_INNINGS_ID NUMBER(11) NOT NULL,
CONSTRAINT FK_GAMES_TEAM FOREIGN KEY (TEAM_ID_1) REFERENCES TEAM(ID),
CONSTRAINT FK_GAMES_TEA FOREIGN KEY (TEAM_ID_2)REFERENCES TEAM(ID),
CONSTRAINT FK_GAMES_VENUE FOREIGN KEY (VENUE_ID)  REFERENCES VENUE(ID),
CONSTRAINT FK_GAMES_OUTCOME FOREIGN KEY  (OUTCOME_ID) REFERENCES  OUTCOME(ID),
CONSTRAINT  FK_GAMES_REFEREE  FOREIGN KEY   (REFEREE_ID_1 )  REFERENCES  REFEREE(ID),
CONSTRAINT  FK_GAMES_REFERE  FOREIGN KEY   (REFEREE_ID_2)  REFERENCES  REFEREE(ID),
CONSTRAINT FK_GAMES_INNINGS  FOREIGN  KEY (FIRST_INNINGS_ID ) REFERENCES   INNINGS(ID)
);
ALTER TABLE EVENT ADD CONSTRAINT FK_EVENT_INNINGS FOREIGN KEY (INNINGS_ID) REFERENCES INNINGS(ID);
ALTER TABLE GAMES ADD CONSTRAINT FK_GAMES_INNINGS_ID FOREIGN KEY (SECOND_INNINGS_ID) REFERENCES INNINGS(ID);

-- 13. **Drop table city**

DROP TABLE CITY;

-- 14. **Drop table innings**
DROP TABLE INNINGS;

-- 15. **Drop table skill**
DROP TABLE SKILLS;

-- 16. **Drop table extra_type**

DROP TABLE EXTRA_TYPE;




